[world]
name = "Kristian's Farmland 4"
description = "Farmland where FOCGs and AWs"
entities = ["player"]
regions = ["farm"]

[entity]
player = { x = "f64", y = "f64" }

[farm]
player = [
	{ x = 0.0, y = 0.0 },
]
